baseURL = "https://blog.tonyding.net/"
DefaultContentLanguage = "zh" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "zh-cn"
title = "Tony Ding's Blog"
copyright = "2022 - 2024 Tony Ding's Blog"
theme = "diary"
# googleAnalytics = "UA-123-45"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
subtitle = "Embrace Everything."
enableAutoDarkMode = true
enableGitalk = true
enableGiscus = false
favicon = "https://onedrive.live.com/embed?resid=EF994429FD9E6DE2%2111979&authkey=%21AEsoCmBydWG1qrQ&width=149&height=149"

# Microsoft Clarity (https://clarity.microsoft.com/) is a free user behavior recording and analytics tool
# clarity = "abcdefghzd"

# Twitter Card and Open Graph settings
enableOpenGraph = false
enableTwitterCards = false
title = "My Blog" # will set 'og:site_name'
description = "My HomePage Description"  # will set 'og:description'

[params.gitalk]
  owner = "MisakaNetworkTD"
  repo = "misakanetworktd.github.io"
  client_id = "Ov23lihbS4RpvRevf8kO"
  client_secret = "ba5bfbd655fdcd4839760cdb341d9631e5ef84cb"
[taxonomies]
   tag = "tags"
   category = "categories"

[params.utterances]
repo="your repo"
term="[ENTER TERM HERE]"
label="your label"
theme="github-light"

# Please visit https://giscus.app/ to generate settings.
[params.giscus]
    data_repo="username/repo"
    data_repo_id="**************************"    
    data_category="General"
    data_category_id="*********************"
    data_mapping="pathname"
    data_strict="0"
    data_reactions_enabled="1"
    data_emit_metadata="0"
    data_input_position="bottom"
    data_theme="preferred_color_scheme"
    data_lang="en"
    crossorigin="anonymous"


[[menu.main]]
url = "/"
name = "主页"
weight = 1
[[menu.main]]
url = "/about"
name = "关于"
weight = 2
[[menu.main]]
url = "/friends"
name = "友情链接"
weight = 3
[[menu.main]]
url = "/index.xml"
name = "RSS 订阅"
weight = 4

[sitemap]
  changeFreq = 'daily'
  disable = false
  filename = 'sitemap.xml'
  priority = -1